global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'your_app'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8080'] # Например: ['localhost:8080']
    metrics_path: '/metrics' # Стандартный эндпоинт для Prometheus